#---------------------------
# check status
#---------------------------
- name: ckeck installed nginx
  shell:  |
    /usr/sbin/nginx -v
  register: has_nginx
  changed_when: False
  ignore_errors: yes

#---------------------------
# install
#---------------------------
- name: install nginx
  command: amazon-linux-extras install -y nginx1 
  become: yes
  when: has_nginx is failed

