#---------------------------
# check status
#---------------------------

#ディレクトリが存在するか
- name: check has directory var/www
  stat:
    path: /var/www/rails_app
  register: has_directory_srv

- name: check has Gemfile
  stat:
    path: /var/www/rails_app/Gemfile
  register: has_directory_gemfile

#クローンされているか
- name: check has directory rails-app
  stat:
    path: /var/www/rails_app/app
  register: was_cloned_rails

#---------------------------
# install
#---------------------------

- name: install mysql
  yum:
    name:
      - mysql
      - mysql-devel
    state:  installed
  become: yes

- name: create dir for rails-app
  file:
    path: /var/www/rails_app
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0775
  become: yes
  when: not has_directory_srv.stat.exists

- name: clone rails-app
  git:
    repo: https://github.com/dai-fuji/rails_practice.git
    dest: /var/www/rails_app
  when: not was_cloned_rails.stat.exists

- name: Install version 2.2.17 of bundler
  community.general.gem:
    name: bundler
    executable: ~/.rbenv/shims/gem
    version: 2.2.17
    state: present

- name: install gems
  shell:  |
    ~/.rbenv/shims/bundle install
  args:
    chdir: /var/www/rails_app
  when: not was_cloned_rails.stat.exists or has_directory_gemfile.stat.exists

- name: install webpacker
  shell: |
    ~/.rbenv/shims/bundle exec rails webpacker:install
  args:
    chdir: /var/www/rails_app
  when: not was_cloned_rails.stat.exists or has_directory_gemfile.stat.exists




